#### Numpy
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [3]:
!pip install numpy

177.24s - pydevd: Sending message related to process being replaced timed-out after 5 seconds


In [4]:
import numpy as np

## create array using numpy
##create a 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [6]:
import numpy as np
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)
print(arr1)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
[1 2 3 4 5]


In [5]:
## 1 d array
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)  ##1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [6]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [7]:
## 2d array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [8]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [9]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
## Attributes of Numpy Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)  # Output: (2, 3)
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)  # Output: int32 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)  # Output: 8 (may vary based on platform)


Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [12]:
### Numpy Vectorized Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

### Element Wise addition
print("Addition:", arr1+arr2)

## Element Wise Substraction
print("Substraction:", arr1-arr2)

# Element-wise multiplication
print("Multiplication:", arr1 * arr2)

# Element-wise division
print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [13]:
## Universal Function
arr=np.array([2,3,4,5,6])
## square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

## natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [14]:
## array slicing and Indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)



Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [16]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [17]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [18]:
## Modify array elements
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [19]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [20]:
### statistical concepts--Normalization
##to have a mean of 0 and standard deviation of 1
data = np.array([1, 2, 3, 4, 5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)



Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [21]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)



Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [22]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])

In [25]:
## rank : rank  of array is simply number of axies or dimension 
## 1 row so 1 rank

## numpy.fromiter(): The fromiter() function create a new one-dimensional array from an iterable object.
## Syntax: numpy.fromiter(iterable, dtype, count=-1)

In [ ]:
import numpy as np

var = "Geekforgeeks"

arr = np.fromiter(var, dtype = 'U2')

print("fromiter() array :",
      arr)

fromiter() array : ['G' 'e' 'e' 'k' 'f' 'o' 'r' 'g' 'e' 'e' 'k' 's']


NumPy Array Broadcasting

Broadcasting in NumPy allows us to perform arithmetic operations on arrays of different shapes without reshaping them. It automatically adjusts the smaller array to match the larger array's shape by replicating its values along the necessary dimensions. This makes element-wise operations more efficient by reducing memory usage and eliminating the need for loops. In this article, we will see how broadcasting works.

In [27]:
import numpy as np

array_2d = np.array([[1, 2, 3], [4, 5, 6]])  
scalar = 10  

result = array_2d + scalar
print(result)

[[11 12 13]
 [14 15 16]]


## Working of Broadcasting in NumPy

Broadcasting applies specific rules to find whether two arrays can be aligned for operations or not that are:

    Check Dimensions: Ensure the arrays have the same number of dimensions or expandable dimensions.
    Dimension Padding: If arrays have different numbers of dimensions the smaller array is left-padded with ones.
    Shape Compatibility: Two dimensions are compatible if they are equal or one of them is 1.

If these conditions aren’t met NumPy will raise a ValueError.

In [28]:
## Example 1: Broadcasting a Scalar to a 1D Array

## It creates a NumPy array arr with values [1, 2, 3]. It adds a scalar value 1 to each element of the array using broadcasting.
import numpy as np
arr = np.array([1, 2, 3])

res = arr + 1  
print(res)

[2 3 4]


In [29]:
## Example 2: Broadcasting a 1D Array to a 2D Array

## This example shows how a 1D array a1 is added to a 2D array a2. NumPy automatically expands the 1D array along the rows of the 2D array to perform element-wise addition.
import numpy as np

a1 = np.array([2, 4, 6])
a2 = np.array([[1, 3, 5], [7, 9, 11]])
res = a1 + a2
print(res)

[[ 3  7 11]
 [ 9 13 17]]


In [ ]:
# Example 3: Broadcasting in Conditional Operations

# We may need to apply a condition to an entire array or a subset of it. Broadcasting can help to perform these operations efficiently without needing loops.
import numpy as np

ages = np.array([12, 24, 35, 45, 60, 72])

age_group = np.array(["Adult", "Minor"])

result = np.where(ages > 18, age_group[0], age_group[1])

print(result)

In [ ]:
#In this example, broadcasting is used to efficiently check which elements in the ages array are greater than 18. Instead of looping through the array the condition is applied across the entire array using NumPy’s where() function. Result is an array of 'Adult' or 'Minor' based on the ages.

In [30]:
# Example 4: Using Broadcasting for Matrix Multiplication

# In this example, each element of a 2D matrix is multiplied by the corresponding element in a broadcasted vector.
import numpy as np
matrix = np.array([[1, 2], [3, 4]])
vector = np.array([10, 20])
result = matrix * vector
print(result)

[[10 40]
 [30 80]]


The 1D vector is broadcasted across the rows of the 2D matrix matrix. This allows element-wise multiplication of corresponding elements between the matrix and the vector.

Example 5: Scaling Data with Broadcasting

Consider a real-world scenario where we need to calculate the total calories in foods based on the amount of fats, proteins and carbohydrates. Each nutrient has a specific caloric value per gram.

    Fats: 9 calories per gram (CPG)
    Proteins: 4 CPG
    Carbohydrates: 4 CPG

Example 6: Adjusting Temperature Data Across Multiple Locations

Suppose you have a 2D array representing daily temperature readings across multiple cities and you want to apply a correction factor to each city’s temperature data.

In [31]:
import numpy as np

temperatures = np.array([
    [30, 32, 34, 33, 31],  
    [25, 27, 29, 28, 26], 
    [20, 22, 24, 23, 21]  
])

corrections = np.array([1.5, -0.5, 2.0])

adjusted_temperatures = temperatures + corrections[:, np.newaxis]
print(adjusted_temperatures)

[[31.5 33.5 35.5 34.5 32.5]
 [24.5 26.5 28.5 27.5 25.5]
 [22.  24.  26.  25.  23. ]]


The correction factors for each city are broadcasted to match the shape of the temperatures array.

Example 7: Normalizing Image Data

Normalization is important in many real-world scenarios like image processing and machine learning because it:

    Centers data by subtracting the mean by ensuring features have zero mean.
    Scales data by dividing by the standard deviation by ensuring features have unit variance.
    Improves numerical stability and performance of algorithms like gradient descent.

Let's see how broadcasting simplifies normalization:

In [32]:
import numpy as np

image = np.array([
    [100, 120, 130],
    [90, 110, 140],
    [80, 100, 120]
])

mean = image.mean(axis=0)   
std = image.std(axis=0)    

normalized_image = (image - mean) / std
print(normalized_image)

[[ 1.22474487  1.22474487  0.        ]
 [ 0.          0.          1.22474487]
 [-1.22474487 -1.22474487 -1.22474487]]


Example 8: Centering Data in Machine Learning

Centering data is an important step in many machine learning workflows. Broadcasting helps center the data efficiently by subtracting the mean from each feature.

In [33]:
import numpy as np

data = np.array([
    [10, 20],
    [15, 25],
    [20, 30]
])

feature_mean = data.mean(axis=0)

centered_data = data - feature_mean
print(centered_data)

[[-5. -5.]
 [ 0.  0.]
 [ 5.  5.]]


It allows us to subtract the mean of each feature from the corresponding values in the data helps in efficiently centering the data without needing loops.

Broadcasting in NumPy helps in efficient data manipulation which makes complex operations on arrays of different shapes both straightforward and computationally efficient.